# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cad2319afed7d2d5ae1d3f08d45ddfa2b349e5d8e258cc8ffb9b83653058655dd6dd2c22d4e58f0e41f7114f6a2df2af3377494c0248ea89f2ee7b0e5362196c

test:
  secret_key_base: d71af081185aac1a4e02d34bb647033459a514bff29914d2093388bcbcae6b1f67f4bff8005c49d5bda1644142ea03ea7919018c6ae1fb333efb78cc7b433d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
